joaov@joaovm1:~/rsc2/theCpart/wmde$ gcc sprite_test.c -o sprite_test.o -O2 -lm -g In file included from sprite_test.c:7:0: include/de.h: In function ‘draw_window’: include/de.h:36:5: warning: implicit declaration of function ‘c_gotoxy’ [-Wimplicit-function-declaration]      c_gotoxy(x, y);      ^ include/de.h: In function ‘draw_clock_widget’: include/de.h:103:14: warning: implicit declaration of function ‘strlen’ [-Wimplicit-function-declaration]      time_str[strlen(time_str) - 1] = '\0';               ^ include/de.h:103:14: warning: incompatible implicit declaration of built-in function ‘strlen’ include/de.h:103:14: note: include ‘<string.h>’ or provide a declaration of ‘strlen’ include/de.h: In function ‘getfield’: include/de.h:198:13: warning: implicit declaration of function ‘strtok’ [-Wimplicit-function-declaration]   for (tok = strtok(line, ";");              ^ include/de.h:198:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]   for (tok = strtok(line, ";");            ^ include/de.h:200:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]     tok = strtok(NULL, ";\n"))         ^ include/de.h: In function ‘draw_graph2d_line’: include/de.h:236:19: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]        char *tmp = strdup(line);                    ^ include/de.h:236:19: warning: incompatible implicit declaration of built-in function ‘strdup’ In file included from include/hicolor.h:10:0,                  from sprite_test.c:8: include/de.h: In function ‘draw_clock_widget’: include/de.h:103:14: warning: incompatible implicit declaration of built-in function ‘strlen’      time_str[strlen(time_str) - 1] = '\0';               ^ include/de.h:103:14: note: include ‘<string.h>’ or provide a declaration of ‘strlen’ include/de.h: In function ‘getfield’: include/de.h:198:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]   for (tok = strtok(line, ";");            ^ include/de.h:200:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]     tok = strtok(NULL, ";\n"))         ^ include/de.h: In function ‘draw_graph2d_line’: include/de.h:236:19: warning: incompatible implicit declaration of built-in function ‘strdup’        char *tmp = strdup(line);                    ^ In file included from include/hicolor.h:11:0,                  from sprite_test.c:8: include/../../kernel_syscalls.h: In function ‘ch_charset437’: include/../../kernel_syscalls.h:25:10: warning: missing terminating " character   __asm__("mov ax, 0x0003 ; vid mode 3 (80x25 color text)\n\t           ^ include/../../kernel_syscalls.h:25:2: error: missing terminating " character   __asm__("mov ax, 0x0003 ; vid mode 3 (80x25 color text)\n\t   ^ In file included from sprite_test.c:8:0: include/hicolor.h: In function ‘calc_icon_grid_desktop’: include/hicolor.h:66:19: error: invalid storage class for function ‘color_distance’  static inline int color_distance(Color a, Color b) {                    ^ sprite_test.c: In function ‘main’: sprite_test.c:11:23: error: invalid initializer   Sprite displaytest = malloc(sizeof(Sprite));                        ^ sprite_test.c:18:15: error: invalid type argument of ‘->’ (have ‘Sprite {aka struct <anonymous>}’)     displaytest->x = i;                ^ sprite_test.c:19:15: error: invalid type argument of ‘->’ (have ‘Sprite {aka struct <anonymous>}’)     displaytest->y = j-i;                ^ sprite_test.c:20:15: error: invalid type argument of ‘->’ (have ‘Sprite {aka struct <anonymous>}’)     displaytest->rgb[j][j][j] = rand%(255);                ^ sprite_test.c:20:36: error: invalid operands to binary % (have ‘int (*)(void)’ and ‘int’)     displaytest->rgb[j][j][j] = rand%(255);                                     ^ sprite_test.c: In function ‘calc_icon_grid_desktop’: sprite_test.c:24:1: error: expected declaration or statement at end of input  }  ^ sprite_test.c: In function ‘calc_icon_grid_desktop’: sprite_test.c:24:1: error: expected declaration or statement at end of input joaov@joaovm1:~/rsc2/theCpart/wmde$
[graph2d] floats! (let's LATER unhardcode this from the lettuce)

Signed-off-by: df42Karazal <176348199+df42Karazal@users.noreply.github.com>

 Please enter the commit message for your changes. Lines starting
 with '' will be ignored, and an empty message aborts the commit.

 Date:      Tue Nov 4 20:16:29 2025 -0300

 On branch main
 Your branch is up-to-date with 'origin/main'.

 Changes to be committed:
	new file:   theCpart/codepageusoem.asm
	modified:   theCpart/interpreter.c
	deleted:    theCpart/interpreter.o
	modified:   theCpart/kernel_syscalls.h
	modified:   theCpart/lechuga.csv
	modified:   theCpart/syscall_list.txt
	modified:   theCpart/wmde/include/de.h
	modified:   theCpart/wmde/include/hicolor.h
	new file:   theCpart/wmde/sprite_test.c